=== pgxn/meta/schema/v2/base.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://pgxn.org/meta/v2/base.schema.json",
  "title": "Base Schema",
  "description": "This is the v2 base distribution schema, mixed into other schemas",
  "type": "object",
  "properties": {
    "name": {
      "$ref": "term.schema.json",
      "description": "The name of the package provided by the distribution. This is usually the same as the name of the “main extension” in the contents of the package but **MAY** be completely unrelated. This value will be used in the distribution file name on [PGXN](https://pgxn.org).",
      "examples": ["pgTAP", "vector"]
    },
    "version": {
      "$ref": "semver.schema.json",
      "description": "The version of the distribution to which the metadata structure refers. Its values **MUST** be a [SemVer](https://semver.org/).\n\nAll of the items listed in `contents will be considered to have this version; any references they make to a version, such as the control file, **SHOULD** be compatible with this version."
    },
    "abstract": {
      "description": "A short description of the purpose of the package provided by the distribution.",
      "type": "string",
      "minLength": 1,
      "examples": [
        "Unit testing for PostgreSQL",
        "Open-source vector similarity search for Postgres"
      ]
    },
    "maintainers": { "$ref": "maintainers.schema.json" },
    "license": { "$ref": "license.schema.json" },
    "contents": { "$ref": "contents.schema.json" },
    "meta-spec": { "$ref": "meta-spec.schema.json" },
    "description": {
      "description": "A longer, more complete description of the purpose or intended use of the package provided by the distribution,answering the question “what is this thing and what value is it?”",
      "type": "string",
      "minLength": 1,
      "examples": [
        "pgTAP is a suite of database functions that make it easy to write TAP-emitting unit tests in psql scripts or xUnit-style test functions."
      ]
    },
    "producer": {
      "description": "The **Producer** that created the metadata. There are no defined semantics for this property, but it is traditional to use a string in the form “Software package version 1.23.0”, or the maintainer's name if the metadata was generated by hand.",
      "type": "string",
      "minLength": 1,
      "examples": ["pgxn CLI version 2.0.4"]
    },
    "classifications": { "$ref": "classifications.schema.json" },
    "ignore": { "$ref": "ignore.schema.json" },
    "dependencies": { "$ref": "dependencies.schema.json" },
    "resources": { "$ref": "resources.schema.json" },
    "artifacts": { "$ref": "artifacts.schema.json" }
  },
  "patternProperties": { "^[xX]_.": { "description": "Custom key" } },
  "required": [
    "name",
    "version",
    "abstract",
    "maintainers",
    "license",
    "contents",
    "meta-spec"
  ],
  "examples": [
    {
      "name": "pgTAP",
      "abstract": "Unit testing for PostgreSQL",
      "description": "pgTAP is a suite of database functions that make it easy to write TAP-emitting unit tests in psql scripts or xUnit-style test functions.",
      "version": "0.26.0",
      "maintainers": [
        { "name": "Josh Berkus", "email": "jberkus@pgxn.org" },
        { "name": "David E. Wheeler", "url": "https://pgxn.org/user/theory" }
      ],
      "license": "MIT OR PostgreSQL",
      "dependencies": {
        "postgres": { "version": "8.4" },
        "packages": {
          "run": {
            "requires": {
              "pkg:postgres/plpgsql": 0
            }
          }
        }
      },
      "contents": {
        "extensions": {
          "pgtap": {
            "abstract": "Unit testing for PostgreSQL",
            "sql": "pgtap.sql",
            "control": "pgtap.control"
          }
        }
      },
      "resources": {
        "homepage": "https://pgtap.org",
        "issues": "https://github.com/theory/pgtap/issues",
        "repository": "https://github.com/theory/pgtap",
        "docs": "https://pgtap.org/documentation.html",
        "support": "https://github.com/theory/pgtap",
        "badges": [
          {
            "src": "https://img.shields.io/badge/License-PostgreSQL-blue.svg",
            "alt": "PostgreSQL License",
            "url": "https://www.postgresql.org/about/licence/"
          },
          {
            "src": "https://github.com/theory/pgtap/actions/workflows/test.yml/badge.svg",
            "alt": "Test Status",
            "url": "https://github.com/theory/pgtap/actions/workflows/ci.yml"
          }
        ]
      },
      "producer": "David E. Wheeler",
      "meta-spec": {
        "version": "2.0.0",
        "url": "https://rfcs.pgxn.org/0003-meta-spec-v2.html"
      },
      "classifications": {
        "tags": [
          "testing",
          "unit testing",
          "tap",
          "tddd",
          "test driven database development"
        ],
        "categories": ["Tooling and Admin"]
      }
    }
  ]
}

=== pgxn/meta/tests/corpus/v2/postgresml.json
{
  "name": "pgml",
  "version": "2.8.2",
  "abstract": "pgml: Created by the PostgresML team",
  "maintainers": [
    {
      "name": "the PostgresML team",
      "url": "https://github.com/postgresml/postgresml/"
    }
  ],
  "license": "MIT",
  "contents": {
    "extensions": {
      "pgml": {
        "sql": "target/release/**/pgml--2.7.13.sql",
        "control": "target/release/**/pgml.control"
      }
    },
    "modules": {
      "pgml": {
        "type": "extension",
        "lib": "target/release/pgml",
        "preload": "server"
      }
    }
  },
  "dependencies": {
    "postgres": {
      "version": "9.1.0"
    },
    "pipeline": "pgrx",
    "packages": {
      "configure": {
        "requires": {
          "pkg:generic/cmake": 0,
          "pkg:cargo/cargo-pgrx": "0.11.2"
        }
      },
      "build": {
        "requires": {
          "pkg:generic/cargo": 0,
          "pkg:generic/bison": 0,
          "pkg:generic/flex": 0,
          "pkg:generic/clang": 0,
          "pkg:generic/openblas": 0,
          "pkg:generic/python3": "3.7",
          "pkg:generic/readline": 0,
          "pkg:generic/openssl": 0,
          "pkg:generic/pkg-config": 0
        }
      },
      "run": {
        "requires": {
          "pkg:generic/openblas": 0,
          "pkg:generic/python3": "3.7",
          "pkg:generic/readline": 0,
          "pkg:generic/openssl": 0
        },
        "recommends": {
          "pkg:pypi/pyarrow": "11.0.0",
          "pkg:pypi/catboost": 0,
          "pkg:pypi/lightgbm": 0,
          "pkg:pypi/torch": 0,
          "pkg:pypi/torchaudio": 0,
          "pkg:pypi/torchvision": 0,
          "pkg:pypi/xgboost": 0,
          "pkg:pypi/accelerate": 0,
          "pkg:pypi/bitsandbytes": 0,
          "pkg:pypi/ctransformers": 0,
          "pkg:pypi/huggingface-hub": 0,
          "pkg:pypi/deepspeed": 0,
          "pkg:pypi/einops": 0,
          "pkg:pypi/optimum": 0,
          "pkg:pypi/peft": 0,
          "pkg:pypi/tokenizers": 0,
          "pkg:pypi/transformers": 0,
          "pkg:pypi/transformers-stream-generator": 0,
          "pkg:pypi/InstructorEmbedding": 0,
          "pkg:pypi/sentence-transformers": 0,
          "pkg:pypi/rouge": 0,
          "pkg:pypi/sacrebleu": 0,
          "pkg:pypi/sacremoses": 0,
          "pkg:pypi/datasets": 0,
          "pkg:pypi/orjson": 0,
          "pkg:pypi/langchain": 0
        }
      }
    },
    "variations": [
      {
        "where": {
          "platforms": ["linux"]
        },
        "dependencies": {
          "packages": {
            "run": {
              "recommends": {
                "pkg:pypi/auto-gptq": 0,
                "pkg:pypi/xformers": 0
              }
            }
          }
        }
      }
    ]
  },
  "resources": {
    "homepage": "https://postgresml.org/",
    "issues": "https://github.com/postgresml/postgresml/issues",
    "docs": "https://postgresml.org/docs/",
    "support": "https://discord.com/invite/DmyJP3qJ7U",
    "repository": "https://github.com/postgresml/postgresml",
    "badges": [
      {
        "alt": "Tests Passing",
        "src": "https://github.com/postgresml/postgresml/actions/workflows/ci.yml/badge.svg",
        "url": "https://github.com/postgresml/postgresml/actions/workflows/ci.yml"
      },
      {
        "alt": "Chat Activity",
        "src": "https://img.shields.io/discord/1013868243036930099",
        "url": "https://discord.gg/DmyJP3qJ7U"
      }
    ]
  },
  "producer": "David E. Wheeler",
  "meta-spec": {
    "version": "2.0.0",
    "url": "https://rfcs.pgxn.org/0003-meta-spec-v2.html"
  },
  "classifications": {
    "tags": ["machine learning", "ml", "transformers"],
    "categories": ["Machine Learning"]
  },
  "artifacts": [
    {
      "type": "source",
      "url": "https://github.com/postgresml/postgresml/archive/refs/tags/v2.8.2.zip",
      "sha256": "2b9d2416096d2930be51e5332b70bcd97846947777a93e4a3d65fe1b5fd7b004"
    },
    {
      "type": "source",
      "url": "https://github.com/postgresml/postgresml/archive/refs/tags/v2.8.2.tar.gz",
      "sha256": "845f28339c6159ac32daccea1cd17b386ea083c3e60bb8d58fb737725afe7eb5"
    }
  ]
}

=== pgxn/meta/tests/corpus/v2/pg_partman.json
{
  "name": "pg_partman",
  "abstract": "Extension to manage partitioned tables by time or ID",
  "version": "5.1.0",
  "maintainers": [
    {
      "name": "Keith Fiske",
      "email": "keith@keithf4.com"
    }
  ],
  "license": "PostgreSQL",
  "contents": {
    "extensions": {
      "pg_partman": {
        "control": "pg_partman.control",
        "sql": "sql/types/types.sql",
        "doc": "doc/pg_partman.md",
        "abstract": "Extension to manage partitioned tables by time or ID"
      }
    },
    "modules": {
      "pg_partman_bgw": {
        "type": "bgw",
        "lib": "src/pg_partman_bgw",
        "preload": "server"
      }
    },
    "apps": {
      "check_unique_constraint": {
        "lang": "python",
        "bin": "bin/common/check_unique_constraint.py",
        "abstract": "Check that all rows in a partition set are unique for the given columns"
      },
      "dump_partition": {
        "lang": "python",
        "bin": "bin/common/dump_partition.py",
        "abstract": "Dump out and then drop all tables contained in a schema."
      },
      "vacuum_maintenance": {
        "lang": "python",
        "bin": "bin/common/vacuum_maintenance.py",
        "abstract": "Performing vacuum maintenance on to avoid excess vacuuming and transaction id wraparound issues"
      }
    }
  },
  "dependencies": {
    "postgres": {
      "version": "14.0"
    },
    "packages": {
      "run": {
        "requires": {
          "pkg:generic/python": "2.0",
          "pkg:pypi/psycopg2": 0
        },
        "recommends": {
          "pkg:pgxn/pg_jobmon": "1.4.1"
        }
      }
    }
  },
  "resources": {
    "issues": "https://github.com/theory/pg-envvar/issues/",
    "repository": "https://github.com/theory/pg-envvar/",
    "badges": [
      {
        "alt": "CI Status",
        "src": "https://github.com/theory/pg-envvar/actions/workflows/ci.yml/badge.svg",
        "url": "https://github.com/theory/pg-envvar/actions/workflows/ci.yml"
      }
    ]
  },
  "producer": "David E. Wheeler",
  "meta-spec": {
    "version": "2.0.0",
    "url": "https://rfcs.pgxn.org/0003-meta-spec-v2.html"
  },
  "classifications": {
    "categories": ["Orchestration"],
    "tags": [
      "partition",
      "partitions",
      "partitioning",
      "table",
      "tables",
      "bgw",
      "background worker",
      "custom background worker"
    ]
  }
}

=== pgxn/meta/tests/corpus/v2/typical-c.json
{
  "name": "envvar",
  "abstract": "Get the value of a server environment variable",
  "description": "Provides a function that returns the value of an environment variable set on the Postgres server.",
  "version": "1.0.0",
  "maintainers": [
    {
      "name": "David E. Wheeler",
      "email": "david@justatheory.com"
    }
  ],
  "license": "PostgreSQL",
  "contents": {
    "extensions": {
      "envvar": {
        "abstract": "Get the value of a server environment variable",
        "control": "envvar.control",
        "sql": "sql/envvar.sql",
        "doc": "doc/envvar.md"
      }
    },
    "modules": {
      "envvar": {
        "type": "extension",
        "lib": "src/envvar"
      }
    }
  },
  "dependencies": {
    "postgres": {
      "version": "9.1.0"
    }
  },
  "resources": {
    "issues": "https://github.com/theory/pg-envvar/issues/",
    "repository": "https://github.com/theory/pg-envvar/",
    "badges": [
      {
        "alt": "CI Status",
        "src": "https://github.com/theory/pg-envvar/actions/workflows/ci.yml/badge.svg",
        "url": "https://github.com/theory/pg-envvar/actions/workflows/ci.yml"
      }
    ]
  },
  "producer": "David E. Wheeler",
  "meta-spec": {
    "version": "2.0.0",
    "url": "https://rfcs.pgxn.org/0003-meta-spec-v2.html"
  },
  "classifications": {
    "categories": ["Data and Transformations"],
    "tags": ["environment variable", "environment", "server"]
  },
  "artifacts": [
    {
      "type": "source",
      "url": "https://github.com/theory/pg-envvar/releases/download/v1.0.0/envvar-1.0.0.zip",
      "sha256": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
    }
  ]
}

=== pgxn/meta/tests/corpus/v2/typical-sql.json
{
  "name": "pair",
  "abstract": "A key/value pair data type",
  "description": "This library contains a single PostgreSQL extension, a key/value pair data type called “pair”, along with a convenience function for constructing key/value pairs.",
  "version": "0.1.8",
  "maintainers": [
    {
      "name": "David E. Wheeler",
      "email": "david@justatheory.com"
    }
  ],
  "license": "PostgreSQL",
  "contents": {
    "extensions": {
      "pair": {
        "abstract": "A key/value pair data type",
        "sql": "sql/pair.sql",
        "doc": "doc/pair.md",
        "control": "pair.control",
        "tle": true
      }
    }
  },
  "dependencies": {
    "postgres": {
      "version": "9.1.0"
    }
  },
  "resources": {
    "issues": "https://github.com/theory/kv-pair/issues/",
    "repository": "https://github.com/theory/kv-pair/",
    "badges": [
      {
        "alt": "Test Status",
        "src": "https://github.com/theory/kv-pair/workflows/CI/badge.svg",
        "url": "https://github.com/theory/kv-pair/actions"
      }
    ]
  },
  "producer": "David E. Wheeler",
  "meta-spec": {
    "version": "2.0.0",
    "url": "https://rfcs.pgxn.org/0003-meta-spec-v2.html"
  },
  "classifications": {
    "categories": ["Data and Transformations"],
    "tags": [
      "variadic function",
      "ordered pair",
      "pair",
      "key value",
      "key value pair"
    ]
  },
  "artifacts": [
    {
      "type": "source",
      "url": "https://github.com/theory/kv-pair/releases/download/v0.1.7/pair-0.1.7.zip",
      "sha256": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
    }
  ]
}

=== pgxn/meta/corpus/v2/custom-fields.json
{
  "name": "widget",
  "abstract": "Widget for PostgreSQL",
  "description": "¿A widget is just thing thing, yoŭ know?",
  "version": "0.2.5",
  "maintainers": [
    {
      "name": "David E. Wheeler",
      "email": "david@justatheory.com",
      "x_looking_for_jobs": false
    }
  ],
  "license": "PostgreSQL",
  "contents": {
    "extensions": {
      "pair": {
        "sql": "sql/widget.sql",
        "control": "widget.control"
      }
    },
    "modules": {
      "examples": {
        "type": "extension",
        "lib": "target/release/example",
        "preload": "server",
        "x_is_c_only": false
      }
    },
    "x_contains_shared_objects": true
  },
  "resources": {
    "homepage": "http://widget.example.org/",
    "x_support_email": "widget@example.org",
    "badges": [
      {
        "alt": "CI Status",
        "src": "https://github.com/example/pg-widget/actions/workflows/ci.yml/badge.svg",
        "url": "https://github.com/example/pg-widget/actions/workflows/ci.yml",
        "x_updated_every": "1h"
      }
    ]
  },
  "dependencies": {
    "postgres": {
      "version": "14.0",
      "X_RELEASE": "REL_14_BETA3"
    },
    "x_forbid_unsafe": true,
    "packages": {
      "run": {
        "requires": {
          "pkg:generic/python": "2.0",
          "pkg:pypi/psycopg2": 0
        },
        "recommends": {
          "pkg:pgxn/pg_jobmon": "1.4.1"
        }
    },
    "x_requires_python": true
    },
    "variations": [
      {
        "where": {
          "platforms": ["linux"]
        },
        "dependencies": {
          "packages": {
            "build": {
              "x_early": true,
              "requires": {
                "pkg:generic/awk": 0,
                "pkg:generic/perl": "5.20"
              }
            },
            "run": {
              "recommends": {
                "pkg:pypi/widgets": 0
              }
            }
          }
        }
      }
    ]
  },
  "classifications": {
    "categories": ["Data and Transformations"],
    "tags": [
      "variadic function"
    ],
    "x_ui_related": true
  },
  "meta-spec": { "version": "2.0.0" }
}

=== pgxn/meta/corpus/v2/typical-pgrx.json
{
  "name": "jsonschema",
  "abstract": "JSON Schema validation functions for PostgreSQL",
  "description": "The jsonschema extension provides JSON Schema validation functions supporting drafts 2020-12, 2019-09, 7, 6, and 4",
  "version": "0.1.1",
  "maintainers": [
    {
      "name": "David E. Wheeler",
      "email": "david@justatheory.com"
    },
    {
      "name": "Tembo",
      "email": "admin+pgxn@tembo.io"
    }
  ],
  "license": "MIT",
  "contents": {
    "extensions": {
      "jsonschema": {
        "abstract": "JSON Schema validation functions for PostgreSQL",
        "doc": "doc/jsonschema.md",
        "sql": "target/release/**/jsonschema--0.1.1.sql",
        "control": "target/release/**/jsonschema.control",
        "x_commit_hash": "4ba6b23"
      }
    },
    "modules": {
      "libjsonschema": {
        "type": "extension",
        "lib": "target/release/libjsonschema"
      }
    }
  },
  "dependencies": {
    "pipeline": "pgrx",
    "postgres": {
      "version": "12.0"
    }
  },
  "resources": {
    "issues": "https://github.com/tembo-io/pg-jsonschema-boon/issues/",
    "repository": "https://github.com/tembo-io/pg-jsonschema-boon/",
    "badges": [
      {
        "alt": "‚öñÔ∏è MIT License",
        "src": "https://img.shields.io/badge/License-MIT-blue.svg",
        "url": "https://github.com/tembo-io/pg-jsonschema-boon/blob/main/LICENSE.md"
      },
      {
        "alt": "üß™ Lint and Test",
        "src": "https://github.com/tembo-io/pg-jsonschema-boon/actions/workflows/lint-and-test.yml/badge.svg",
        "url": "https://github.com/tembo-io/pg-jsonschema-boon/actions/workflows/lint-and-test.yml"
      },
      {
        "alt": "üìä Code Coverage",
        "src": "https://codecov.io/gh/tembo-io/pg-jsonschema-boon/graph/badge.svg",
        "url": "https://codecov.io/gh/tembo-io/pg-jsonschema-boon"
      }
    ]
  },
  "producer": "David E. Wheeler",
  "meta-spec": {
    "version": "2.0.0",
    "url": "https://rfcs.pgxn.org/0003-meta-spec-v2.html"
  },
  "classifications": {
    "categories": ["Data and Transformations"],
    "tags": [
      "jsonschema",
      "validation",
      "json",
      "schema",
      "constraint",
      "pgrx",
      "rust"
    ]
  },
  "artifacts": [
    {
      "type": "source",
      "url": "https://github.com/tembo-io/pg-jsonschema-boon/releases/download/v0.1.1/jsonschema-0.1.1.zip",
      "sha512": "cfd9447575acb764aba6eb01c9c8ce75a5975c3be103d330a6a22b1a5ff85af8392fd348569b0eefd2d033232c0a5bffead3309d9c39759788889b51d79dd6ef"
    }
  ]
}
